### ISSUE TITLE
Add support for specifying query-driver

### ISSUE THREAD

**Issue by hlk09** [bkryza/clang-uml#109]
When using clang-uml in MacOS, sometimes some c headers cannot be found, like `stdarg.h`.
Clangd has the configuration argument `[–query-driver]`, then it will execute drivers and fetch necessary include paths to compile codes.
Maybe clang-uml can also support this argument so that include paths will be found correctly.

**Comment by bkryza** [comment]
@hlk09 Thanks for the tip - I'll definitely look into that feature.

In the meantime, the following workaround sometimes helps on macOS:

https://github.com/bkryza/clang-uml/blob/master/docs/troubleshooting.md#fatal-error-stddefh-file-not-found

**Comment by bkryza** [comment]
@hlk09 Thanks for the tip on this option - the current master branch now contains [support for this option](https://github.com/bkryza/clang-uml/blob/master/docs/common_options.md#use---query-driver-command-line-option), which works in a similar fashion to the `clangd` implementation (but not exactly)...
