### ISSUE TITLE
Error Generating Diagrams on Windows with `clang-uml`

### ISSUE THREAD

**Issue by DeveloperPaul123** [bkryza/clang-uml#110]
**Description**

I'm trying to use the latest release of `clang-uml` with `LLVM` `15.0.7` on Windows 11. I've successfully built my project with `Ninja` and `Clang` and am successfully generating a compilation database; however, when I try to run `clang-uml` I get this error:

```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals_core.h:807:1: error: static_assert failed
      "Error in C++ Standard Library usage."
_EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 15.0.0 or newer.");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals_core.h:462:5: note: expanded from macro
      '_EMIT_STL_ERROR'
    static_assert(false, "Error in C++ Standard Library usage.")`
```

This line can be found [here](https://github.com/microsoft/STL/blob/main/stl/inc/yvals_core.h#L836).

**Comment by bkryza** [comment]
@DeveloperPaul123 I have very little experience with MSVC, however this looks like an issue with actual include paths used when running `clang-uml` are different than those when building your project. 

Can you please try setting this in your CMakeLists.txt, rebuild your project and try again:

```cmake
set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES})
```

If this doesn't help please paste an excerpt from your compilation database maybe I'll notice sth...

**Comment by bkryza** [comment]
Also can you paste the output of:

```bash
clang-uml --version
```

**Comment by DeveloperPaul123** [comment]
> @DeveloperPaul123 I have very little experience with MSVC, however this looks like an issue with actual include paths used when running `clang-uml` are different than those when building your project.
> 
> Can you please try setting this in your CMakeLists.txt, rebuild your project and try again:
> 
> ```cmake
> set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES})
> ```
> 
> If this doesn't help please paste an excerpt from your compilation database maybe I'll notice sth...

I'll work on this and get back to you

> Also can you paste the output of:

Here you go

```
clang-uml 0.3.2
Copyright (C) 2021-2023 Bartek Kryza <bkryza@gmail.com>
Built against LLVM/Clang libraries version: 14.0.6
Using LLVM/Clang libraries version: clang version 14.0.6 (https://github.com/llvm/llvm-project.git f28c006a5895fc0e329fe15fead81e37457cb1d1)
```

**Comment by DeveloperPaul123** [comment]
> set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES})

This did not work, I'm getting the same error. 

Unfortunately I cannot share the compilation database from the project I'm trying this out on. I'll have to try on a different project and let you know if I have the same issues.

**Comment by bkryza** [comment]
@DeveloperPaul123 I've released yesterday a new version of `clang-uml`, and the Windows binary is now built against LLVM 15 - maybe it could resolve the above issue:

https://github.com/bkryza/clang-uml/releases/tag/0.3.3

**Comment by DeveloperPaul123** [comment]
@bkryza This fixed our issue! I was wondering if the LLVM versions needed to match what I was using. In the future I guess we can build `clang-uml` from source to match our local toolchain version. Thanks for providing the new binaries. 

It might also be good to consider providing releases built against multiple versions of the `LLVM` toolkit for the convenience of your users. This could be automated via Github Actions

**Comment by bkryza** [comment]
@DeveloperPaul123 Thanks for checking!

Unfortunately it's not possible to download LLVM toolchain development binary libraries, i.e. you have to build them in GitHub Actions before building `clang-uml` - and that is over 1 hour on my 32vcpu desktop machine... So currently this is not feasible, but I'll consider building separate installers for different LLVM versions for Windows...

**Comment by DeveloperPaul123** [comment]
@bkryza Oh I see, that's quite the task then. In that case maybe that's too much overhead.

**Comment by DeveloperPaul123** [comment]
For posterity, I was able to use clang-uml `0.3.5` on a code base built with clang 16.
