### ISSUE TITLE
Add JSON diagram generator

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#114]
In addition to the PlantUML diagram generator, it would be useful to have a dump of the intermediate model used to generate diagrams in some machine processable format e.g. JSON.

This could be used for scripting, integrations but also debugging and more strict test cases.

**Comment by ahmednofal** [comment]
Hello, wanted to ask you if there is a tool that can render from the JSON output ?

**Comment by bkryza** [comment]
@ahmednofal Not to my knowledge, JSON output is aimed for users who wish to integrate the diagram model into their own custom code documentation or visualization tools. 

It should be rather straightforward to write for instance a Python script that would convert a diagram model from JSON into GraphViz dot format or MermaidJS...
