### ISSUE TITLE
About Sequence Diagram Generation

### ISSUE THREAD

**Issue by 263868161** [bkryza/clang-uml#122]
In the 20001 example.

I modified the t20001.cc and .clang-uml files.

t20001.c:
#include <algorithm>
#include <vector>

namespace clanguml {
namespace t20001 {

namespace detail {
struct C {
    auto add(int x, int y) { return x + y; }
};
}

class A {
public:
    A() { }

    int add(int x, int y) { return m_c.add(x, y); }

    int add3(int x, int y, int z)
    {
        std::vector<int> v;
        v.push_back(x);
        v.push_back(y);
        v.push_back(z);
        auto res = add(v[0], v[1]) + v[2];
        log_result(res);
        return res;
    }

    static void log_result(int r) { }

private:
    detail::C m_c{};
};

class B {
public:
    B(A &a)
        : m_a{a}
    {
    }

    int wrap_add(int x, int y)
    {
        auto res = m_a.add(x, y);
        m_a.log_result(res);
        return res;
    }

    int wrap_add3(int x, int y, int z)
    {
        auto res = m_a.add3(x, y, z);
        m_a.log_result(res);
        return res;
    }

private:
    A &m_a;
};

}
}
using namespace clanguml::t20001;
int tmain()
{
    A a;
    B b(a);

    auto tmp = a.add(1, 2);

    return b.wrap_add3(tmp, 2, 3);
}

 .clang-uml :

compilation_database_dir: ..
output_directory: puml
diagrams:
  t20001_sequence:
    type: sequence
    glob:
      - ../../tests/t20001/t20001.cc
    include:
      namespaces:
        - clanguml::t20001
    exclude:
      namespaces:
        - clanguml::t20001::detail
    using_namespace:
      - clanguml::t20001
    start_from:
      - function: "tmain()"
    plantuml:
      before:
        - "' t20001 test diagram of type {{ diagram.type }}"
      after:
        - '{% set e=element("clanguml::t20001::tmain()") %} note over {{ e.alias) }}: Main test function'

execute command：clang-uml

[info] [tid 18314] [cli_handler.cc:243] Loaded clang-uml config from .clang-uml
[info] [tid 18314] [cli_handler.cc:266] Loading compilation database from /home/hy/git/clang-uml/release/ directory
[info] [tid 18325] [generators.h:237] Generating diagram t20001_sequence
[warning] [tid 18325] [sequence_diagram_generator.cc:403] Failed to find participant with tmain() for start_from condition
[error] [tid 18325] [generators.cc:176] [inja.exception.render_error] (at 1:63) variable 'e.alias' not found

how to solve this problem? Thank you!

**Comment by bkryza** [comment]
@263868161 You've moved the `tmain()` function into the root namespace, however the config file has a following constraint:
```yaml
include:
  namespaces:
    - clanguml::t20001
```

which means it will not consider any elements outside of this namespace. Try the following config file:

```yaml
compilation_database_dir: ..
output_directory: puml
diagrams:
  t20001_sequence:
    type: sequence
    glob:
      - ../../tests/t20001/t20001.cc
    exclude:
      namespaces:
        - clanguml::t20001::detail
        - std
    start_from:
      - function: "tmain()"
    plantuml:
      before:
        - "' t20001 test diagram of type {{ diagram.type }}"
      after:
        - '{% set e=element("tmain()") %} note over {{ e.alias) }}: Main test function'
```

The test case will fail due to different namespace but it generates the following diagram:

```plantuml
@startuml
  ' t20001 test diagram of type sequence
  participant "tmain()" as C_0000468220665220501412 [[https://github.com/bkryza/clang-uml/blob/06fe24f59b8edcdab7589c1fed952e113adbfcd2/tests/t20001/t20001.cc#L65{tmain}]]
  activate C_0000468220665220501412
  participant "clanguml::t20001::A" as C_0001771943546649183134 [[https://github.com/bkryza/clang-uml/blob/06fe24f59b8edcdab7589c1fed952e113adbfcd2/tests/t20001/t20001.cc#L13{A}]]
  C_0000468220665220501412 -> C_0001771943546649183134 [[https://github.com/bkryza/clang-uml/blob/06fe24f59b8edcdab7589c1fed952e113adbfcd2/tests/t20001/t20001.cc#L70{}]] : add(int,int)
  activate C_0001771943546649183134
  C_0001771943546649183134 --> C_0000468220665220501412
  deactivate C_0001771943546649183134
  participant "clanguml::t20001::B" as C_0000272433898507800600 [[https://github.com/bkryza/clang-uml/blob/06fe24f59b8edcdab7589c1fed952e113adbfcd2/tests/t20001/t20001.cc#L36{B}]]
  C_0000468220665220501412 -> C_0000272433898507800600 [[https://github.com/bkryza/clang-uml/blob/06fe24f59b8edcdab7589c1fed952e113adbfcd2/tests/t20001/t20001.cc#L72{}]] : wrap_add3(int,int,int)
  activate C_0000272433898507800600
  C_0000272433898507800600 -> C_0001771943546649183134 [[https://github.com/bkryza/clang-uml/blob/06fe24f59b8edcdab7589c1fed952e113adbfcd2/tests/t20001/t20001.cc#L52{}]] : add3(int,int,int)
  activate C_0001771943546649183134
  C_0001771943546649183134 -> C_0001771943546649183134 [[https://github.com/bkryza/clang-uml/blob/06fe24f59b8edcdab7589c1fed952e113adbfcd2/tests/t20001/t20001.cc#L25{}]] : add(int,int)
  activate C_0001771943546649183134
  C_0001771943546649183134 --> C_0001771943546649183134
  deactivate C_0001771943546649183134
  C_0001771943546649183134 -> C_0001771943546649183134 [[https://github.com/bkryza/clang-uml/blob/06fe24f59b8edcdab7589c1fed952e113adbfcd2/tests/t20001/t20001.cc#L26{}]] : __log_result(int)__
  activate C_0001771943546649183134
  deactivate C_0001771943546649183134
  C_0001771943546649183134 --> C_0000272433898507800600
  deactivate C_0001771943546649183134
  C_0000272433898507800600 -> C_0001771943546649183134 [[https://github.com/bkryza/clang-uml/blob/06fe24f59b8edcdab7589c1fed952e113adbfcd2/tests/t20001/t20001.cc#L53{}]] : __log_result(int)__
  activate C_0001771943546649183134
  deactivate C_0001771943546649183134
  C_0000272433898507800600 --> C_0000468220665220501412
  deactivate C_0000272433898507800600
  deactivate C_0000468220665220501412
   note over C_0000468220665220501412: Main test function
  @enduml

```
