### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by 263868161** [bkryza/clang-uml#123]
When I execute the instruction to compile the code https://github.com/bkryza/clang-uml-examples，
The error is as follows：
cd clang-uml && \
	../../../clang-uml/release/src/clang-uml --output-directory ../puml
[info] [tid 44679] [cli_handler.cc:243] Loaded clang-uml config from .clang-uml
[info] [tid 44679] [cli_handler.cc:266] Loading compilation database from /home/hy/git/clang-uml-examples/clang-uml/clang-uml/debug directory
[info] [tid 44696] [generators.h:237] Generating diagram package_model_class
[info] [tid 44693] [generators.h:237] Generating diagram decorators_class
[info] [tid 44692] [generators.h:237] Generating diagram config_class
[info] [tid 44695] [generators.h:237] Generating diagram main_package
[info] [tid 44694] [generators.h:237] Generating diagram include_graph
[info] [tid 44691] [generators.h:237] Generating diagram common_model_class
[info] [tid 44690] [generators.h:237] Generating diagram class_model_class
[info] [tid 44697] [generators.h:237] Generating diagram sequence_model_class
[info] [tid 44693] [generators.cc:76] Written decorators_class diagram to ../puml/decorators_class.puml
[info] [tid 44692] [generators.cc:76] Written config_class diagram to ../puml/config_class.puml
[info] [tid 44691] [generators.cc:76] Written common_model_class diagram to ../puml/common_model_class.puml
[info] [tid 44696] [generators.cc:76] Written package_model_class diagram to ../puml/package_model_class.puml
[info] [tid 44697] [generators.cc:76] Written sequence_model_class diagram to ../puml/sequence_model_class.puml
[error] [tid 44690] [generator.h:436] Failed to render PlantUML directive: 
https://github.com/bkryza/clang-uml/blob/{{ git.commit }}/{{ element.source.path }}#L{{ element.source.line }}
 due to: [json.exception.type_error.302] type must be string, but is object
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be string, but is object
Aborted (core dumped)

how to solve this problem？Thank you!

**Comment by bkryza** [comment]
@263868161 It seems I haven't pushed the updated version of `clang-uml-examples` from my desktop to GitHub - it is fixed now.

Please checkout `clang-uml-examples` again, preferably into a clean directory, and then try again...
