### ISSUE TITLE
Thread support and class calling

### ISSUE THREAD

**Issue by franz0272** [bkryza/clang-uml#125]
Hi.
I can not manage generating sequence diagrams following threads execution... Is it possible? Am I wrong?
My C++ code is very "tamed", so that no "namespace" labels are present, but only pure directives. Maybe is that the reason I can not have expected results?
Another problem is for class diagrams: I can not obtain graphs of class where I see which class calls other class(es).
Could you help me, pls?

Thanks,
Franz

**Comment by bkryza** [comment]
@franz0272 

As to the threads, in general the answer is no, I have this on my todo list but haven't figured out how to do this yet - however it might work if you're passing lambdas to threads... So it depends on how you create your threads. Any chance you can share relevant parts of your code here? Maybe I can figure something out...

As to the second problem - what do you mean exactly by `I can not obtain graphs of class where I see which class calls other class`? Class diagrams represent entity-relationships, i.e. they do not convey call-graph information. Maybe you mean [activity diagrams](https://plantuml.com/activity-diagram-legacy), but these are not supported yet...

**Comment by franz0272** [comment]
I'm sorry I can share with you my code, but you already answered me.
For the second problem, I just need relationships I can not obtain... Any suggestion on possibile errors I'm doing?

Thank you so much!

Franz

**Comment by bkryza** [comment]
> I'm sorry I can share with you my code, but you already answered me.

Sure, I understand :-)

> For the second problem, I just need relationships I can not obtain... Any suggestion on possibile errors I'm doing?

Can you please explain a little more, i.e. what are you trying to generate, what do you expect in the diagram (e.g. association relationship between classes `A` and `B` which is in the code but not in the diagram), your `.clang-uml` file and any errors in the output of the tool - if any...
