### ISSUE TITLE
It is possible to provide a bin on MacOS ？

### ISSUE THREAD

**Issue by aierui** [bkryza/clang-uml#13]
🙄 c++ compile very bad.

**Comment by bkryza** [comment]
@aierui Currently binary packages are not available.

However assuming you have a working XCode + homebrew setup, building from sources should work:

First install the dependencies:

```bash
brew install ccache cmake llvm fmt spdlog yaml-cpp
```
and just run:

```bash
make release
```

**Comment by aierui** [comment]
@bkryza  Thank you very much.
