### ISSUE TITLE
Exclude enums in class diagram

### ISSUE THREAD

**Issue by fleroy-witekio** [bkryza/clang-uml#131]
In a class diagram, how can I exclude all the enums?
I thought I had found the solution, but it doesn't work:
in https://github.com/bkryza/clang-uml-examples/blob/master/cppast/.clang-uml there is
```
	exclude:
	  entity_types:
	    - enums
```
but it is not used or documented anywhere else, and it doesn't work when I try it.

(Thank you for this wonderful tool :) )

**Comment by bkryza** [comment]
@fleroy-witekio Sorry this not possible at the moment, I have an issue for this (#100), I'll try to schedule it for the next release - it's been long overdue ;-)

**Comment by bkryza** [comment]
@fleroy-witekio However if your list of enums is not very long, you should be able to exclude them one by one, e.g.:

```yaml
exclude:
  elements: [ns1::enum1, ns2::enum2]
```

**Comment by fleroy-witekio** [comment]
Thanks you, yes I did that for now, I used multi-cursor edition on the generated .puml file to get and format all the enums.

**Comment by fleroy-witekio** [comment]
I had read https://github.com/bkryza/clang-uml/issues/100 but I didn't understood that it was the same problem!

**Comment by bkryza** [comment]
@fleroy-witekio This is now resolved in master branch: https://github.com/bkryza/clang-uml/blob/master/docs/diagram_filters.md#element_types
