### ISSUE TITLE
Exclude classes with wildcard pattern

### ISSUE THREAD

**Issue by fleroy-witekio** [bkryza/clang-uml#132]
In a class diagram, I would like to exclude some classes by using a wildcard pattern, notably all the nested QPrivateSignal classes generated by Qt in QObject derived classes.
I tried with:
```
    exclude:
      elements:
        - *QPrivateSignal
```
but it doesn't work.

**Comment by fleroy-witekio** [comment]
Oh ok.
I think there is cases where regex is useful for that.

**Comment by bkryza** [comment]
@fleroy-witekio This issue is now resolved in `master` branch, it is possible to use regular expressions in diagram filters, for instance to exclude classes, which contain the word `test` use:

```yaml
  exclude:
    elements:
      - r: '.*test.*'
```

See more about it [here](https://github.com/bkryza/clang-uml/blob/master/docs/diagram_filters.md)
