### ISSUE TITLE
Copy/Move constructors and Destructor filter

### ISSUE THREAD

**Issue by thegreathir** [bkryza/clang-uml#145]
Is any filter available to filter out them?

**Comment by bkryza** [comment]
@thegreathir Unfortunately this is not possible yet, the only filter for methods is based on `access`, e.g. "Include only `public` methods`"

**Comment by thegreathir** [comment]
OK, Thank you for your quick response :))
It would be nice to add this feature.

**Comment by bkryza** [comment]
@thegreathir This is now available in `master` branch - see [here](https://github.com/bkryza/clang-uml/blob/master/docs/test_cases/t00067.md) for example...
