### ISSUE TITLE
Support "in-comment" directives (uml note) for sequence diagrams 

### ISSUE THREAD

**Issue by MrChocolateMoose** [bkryza/clang-uml#173]
One of the main use cases our project would like to use `clang-uml` is to document the "intents" of the dynamic behavior using comments while having `clang-uml` keep the actual sequence up to date and handle any updates to the "intents" through reviews. This is due to some stipulations of the regulated industry we are in.

I noticed class diagrams have support for in-comment decoraters, and was hoping something similar could be added to sequence diagrams (since I couldn't get it to work and didn't see support in the baseline).

The features that would be most helpful to my project would be:
- (important) documenting control flow
- (important) documenting function calls
- (nice to have) allowing arbitrary documenting wedged between control flow/function calls

The same syntax used for class diagrams seems applicable.

**Comment by bkryza** [comment]
@MrChocolateMoose I'm not 100% sure if I understand your use case correctly, but I'll assume you meant adding comments above or next to any actual call expressions within a function/method body.

In that case I agree this would be nice thing to have, and I've actually tried to do it before, unfortunately I couldn't figure out how to access arbitrary code comments through LLVM API. 
```cpp
///
/// @brief Function foo
/// 
/// @uml{note[] A comment I have access to.}
///
void foo() {

  // @uml{note[] A comment I don't have currently access to.}
  bar();
}
```

I'm still planning to do it, but sadly I will have to manually parse the code region above (and 'next-to') any call expression, extract the comment contents if any and then extract from it any relevant directives - so I'm not exactly looking forward to doing it...

In my case my main motivation was to:
- extract textual comment of a function or method call in activity and render it on the diagram above the message name
- use comment 'markers' to define the boundaries for a given sequence diagram in addition to function signatures

Could you write a small code fragment which shows how you would like these comments to look like and how should they be rendered in the sequence diagrams?

**Comment by bkryza** [comment]
@MrChocolateMoose As of release 0.4.1, it is possible to add notes in sequence diagrams using comments placed before or next to a call expression.

You can either add a note using `\uml{note TEXT}` in the comment like this:
```cpp
int tmain()
{
    A a;
    B b(a);
 
    // \uml{note Just add 2 numbers}
    auto tmp = a.add(1, 2);
 
    // \uml{note[] And now add another 2}
    return b.wrap_add3(tmp, 2, 3);
}
```
(see [t20001](https://clang-uml.github.io/md_docs_2test__cases_2t20001.html) test case) or enable in your diagram config `generate_message_comments`:

```yaml
    generate_message_comments: true
```
which will generate notes from all comments placed before or next to an specific call expression
 (see [t20038](https://clang-uml.github.io/md_docs_2test__cases_2t20038.html) for an example).
