### ISSUE TITLE
Building from source fails with: error: ‘concept’ does not name a type

### ISSUE THREAD

**Issue by sbmueller** [bkryza/clang-uml#175]
Hi, trying to compile the latest master from source using LLVM 16 on Ubunutu 20, I get the following error during compilation:
```
[ 39%] Building CXX object tests/CMakeFiles/test_cases.dir/t00058/t00058.cc.o
/home/user/src/clang-uml/tests/t00058/t00058.cc:22:1: error: ‘concept’ does not name a type
   22 | concept same_as_first_type = std::is_same_v<std::remove_cvref_t<T>,
      | ^~~~~~~
/home/user/src/clang-uml/tests/t00058/t00058.cc:22:1: note: ‘concept’ only available with ‘-fconcepts’
```
Any idea what might be the problem?

**Comment by bkryza** [comment]
@sbmueller Yes, while `clang-uml` requires only C++17 compiler some test cases require C++20 (e.g. for concepts). It should have been automatically detected that your compiler doesn't have support for them and these test cases should have been skipped. Can you provide more information about the compiler you are using here, you can find it in CMakeCache (assuming you've built it using `make debug`):

```bash
cat debug/CMakeCache.txt | grep CMAKE_CXX_COMPILER:FILEPATH
```

and then run the compiler shown there with `-v` flag.

Also, even though test compilation failed, you already should have a working `clang-uml` binary in:
```bash
debug/src/clang-uml --version
```

**Comment by sbmueller** [comment]
Hi @bkryza , thanks for the response.
You're right, I assumed with specifying the LLVM 16 tool chain, automatically the corresponding compiler is used, which was not the case. Instead, my system gcc 9.4 was used.
By removing the `release` folder and building again with `CXX=/usr/bin/clang++-16 LLVM_VERSION=16 make release` I can proceed further, but still encounter the following error:
```
clang-uml/tests/t00056/t00056.cc:37:44: error: ‘same_as’ in namespace ‘std’ does not name a template type
   37 |                                  } -> std::same_as<std::string>;
      |                                            ^~~~~~~
/home/z628856/src/thirdparty/clang-uml/tests/t00056/t00056.cc:37:51: error: expected ‘}’ before ‘<’ token
```
Also, despite an exectuable being present in the `release/src` folder, the `install` target does not seem to be available:
```
make install
make: *** No rule to make target 'install'.  Stop.
```
Compiling the tests is indeed not that important for me, I just want to install clang-uml in my system path.

**Comment by bkryza** [comment]
@sbmueller There was a header missing in `t00056.cc` (oddly it compiled on my desktop Ubuntu 22.04 and macos), can you please try again with the latest commit?

**Comment by sbmueller** [comment]
@bkryza Thanks, probably due to an indirect include, since I didn't have a `complex` header on my system. I first needed to install libstdc++10, with that compilation succeeds!
Lastly, I think there is still an `install` target missing in the Makefile. https://github.com/bkryza/clang-uml/blob/master/docs/installation.md#linux references this target, but it is actually not found in the Makefile.

**Comment by bkryza** [comment]
@sbmueller Thanks for noticing that, I forgot about this target somehow - it is now in the Makefile, it should work as follows:

```bash
# To build using a specific installed version of LLVM use:
LLVM_VERSION=14 make release

# Optionally, to install in default prefix
make install
# or to install in custom prefix
make install DESTDIR=/opt/clang-uml
```

**Comment by sbmueller** [comment]
Thanks for your help :1st_place_medal: :pray:
