### ISSUE TITLE
Sequence diagram of static variables

### ISSUE THREAD

**Issue by Viren17** [bkryza/clang-uml#181]
When I try to generate a sequence diagram of static class (Singleton) functions, the function call goes through the constructor every time. This clutters the sequence diagram. The attached pdf explains this with a simple example. This was observed on v0.4.0 [on Windows 10]
[static_var_sequence_diag_issue.pdf](https://github.com/bkryza/clang-uml/files/12779157/static_var_sequence_diag_issue.pdf)

**Comment by bkryza** [comment]
@Viren17 Thanks for reporting this, I will look into the possibility of detecting static variable constructors and generating them only once in the diagram.

What you can do for now, is to disable all constructor calls using `callee_types` filter:

```yaml
    exclude:
      callee_types:
        - constructor
```
but of course in this case the constructor will not be included in the diagram at all...

**Comment by bkryza** [comment]
@Viren17 This is now fixed in the master branch, there is also a test case for this: https://github.com/bkryza/clang-uml/blob/master/docs/test_cases/t20037.md
