### ISSUE TITLE
Building release 0.4.0 from source fails on Linux

### ISSUE THREAD

**Issue by njamb94** [bkryza/clang-uml#188]
When trying to build release 0.4.0 from source by following the [instructions detailed here](https://clang-uml.github.io/md_docs_2installation.html#linux), the build fails when trying to build tests .

The build passes for release 0.3.9 and it is possible to install version 0.4.0 from repository "ppa:bkryza/clang-uml", but not from source.

**OS info:**
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```
**Installed packages:**
```
- ccache version: 4.5.1
- cmake version: 3.22.1
- libyaml-cpp-dev: 0.7.0+dfsg-8build1
- clang-12: 12.0.1-19ubuntu3
- libclang-12-dev: 1:12.0.1-19ubuntu3
- libclang-cpp12-dev: 1:12.0.1-19ubuntu3
```
See attached photo for build output (the output is when building was rerun on a single processor):

![clanguml_040_error](https://github.com/bkryza/clang-uml/assets/10185192/52c81a0c-036b-4242-857e-0b34679ca4f3)

**Comment by bkryza** [comment]
@njamb94 Thanks for reporting this. Which compiler and version are you using there? The GitHub Actions (on which it passes) are run on Ubuntu 22.04 and GCC 11: https://github.com/bkryza/clang-uml/blob/master/.github/workflows/build.yml
