### ISSUE TITLE
Check compatibility with gcc 11.3.0

### ISSUE THREAD

**Issue by njamb94** [bkryza/clang-uml#191]
Not sure if the project should be only compiled with _gcc 11.4_ for Linux (Ubuntu 22.04), as [build.yml](https://github.com/bkryza/clang-uml/blob/master/.github/workflows/build.yml) notes only _gcc-11_ as dependency (no patch version).

Building with _gcc v11.3.0_ causes tests to fail when building due to _std::regex::multiline_ not being a member of _'std::__cxx11::regex' {aka std::__cxx11::basic_regex\<char\>'}_.

Specifically failing in _tests/catch.h:13305:26_ when appending
```c
flags |= std::regex::multiline;
```
 in _RegexMatcher::match(std::string const &matchee) const_ function

Building with gcc v11.4.0 passes with no problems.

**Comment by bkryza** [comment]
@njamb94 Thanks, I actually didn't need this line, I've added it for tests at some point but they pass without it so it should work now with earlier GCC versions...
