### ISSUE TITLE
Progress Output Broken in Powershell 7.4.0 

### ISSUE THREAD

**Issue by DeveloperPaul123** [bkryza/clang-uml#218]
I'm using `clang-uml` on Windows 11 with PowerShell (Core) version `7.4.0` and running `clang-uml --progress` looks like this:

![image](https://github.com/bkryza/clang-uml/assets/6591180/a5d7957e-37c1-48d4-8ec5-d652fd14c86c)

Note sure if Windows PowerShell Core is meant to be supports but thought I'd report anyway.

**Comment by bkryza** [comment]
@DeveloperPaul123 Apparently, PowerShell by default uses UTF-16 encoding so the characters were off - I've changed the progress bar characters on Windows to plain ASCII, so it's a little better:

![image](https://github.com/bkryza/clang-uml/assets/5522906/3c130577-0b94-4419-8560-8899032ff59e)

Unfortunately, each progress bar update generates a new line (on Linux and macos they are updated in place, but I'm not sure if this is possible using the [library](https://github.com/p-ranav/indicators) I'm using for this...

**Comment by DeveloperPaul123** [comment]
@bkryza No problem, thanks for the update. 

I believe that should be possible on windows as well, but I haven't run the examples from that library yet. I can give it a try and report here

**Comment by DeveloperPaul123** [comment]
Actually, looks like the samples don't build on Windows with MSVC anyway. I'm giving your latest changes a test though.

**Comment by bkryza** [comment]
@DeveloperPaul123 One more update here, I've tried also running `clang-uml` in a Powershell session in [Windows Terminal](https://github.com/microsoft/terminal) and the progress is updated correctly inline without creating new lines for each update:

![image](https://github.com/bkryza/clang-uml/assets/5522906/12654b4f-e83a-4e55-a68e-702009c05c78)
