### ISSUE TITLE
Add support for LLVM12 static linkage

### ISSUE THREAD

**Issue by njamb94** [bkryza/clang-uml#225]
Hello,

On Linux 22.04, at the moment, it is not possible to statically link LLVM12 due to _clangSupport_ library in _LLVMSetup.cmake_ file. (See make output: [link_llvm12_static.log](https://github.com/bkryza/clang-uml/files/13873218/link_llvm12_static.log))

From my point of view, the fix lies in modifying _LLVMSetup.cmake_ file to exclude _clangSupport_ library if LLVM version is bellow 15 (like it is done for MSVC):
![link_llvm12_static_fix](https://github.com/bkryza/clang-uml/assets/10185192/7780f62e-87f6-4a4d-a859-6c4bb8f66835)

The choice for llvm static linkage was done by modifying options in CMakeLists.txt:
![option_link_llvm_shared_off](https://github.com/bkryza/clang-uml/assets/10185192/d06a69b7-431a-4be9-bd2c-e31c135c364b)

Question: would it make more sense to make llvm linkage type configurable from the Makefile?
Something like this:
![makefile_duse_shared_llvm](https://github.com/bkryza/clang-uml/assets/10185192/fe9bfa90-c4d6-49c1-bd31-523e9cc102e2)

**Comment by bkryza** [comment]
@njamb94 I'll look into this, I'll have to check how this affects `macos` and `MSVC` targets.
