### ISSUE TITLE
something seems wrong in documentation for Interactive SVG diagrams

### ISSUE THREAD

**Issue by apfreelancing** [bkryza/clang-uml#226]
i was trying to implement links and tooltips like you proposed in the documentation:
 `tooltip: '{% if "comment" in element %}{{ abbrv(trim(replace(element.comment, "\n+", " ")), 256) }}{% else %}{{ element.name }}{% endif %}'`
but jinja kept telling me 
`[error] [tid 1245886] [generators.cc:265] [json.exception.type_error.302] type must be string, but is object`

i figured out to instead use "element.comment.formatted" so i guess "element.comment" is an object, not a string in my case.

**Comment by bkryza** [comment]
@apfreelancing Thanks, I've fixed it in my branch. The full reference on how to use these templates is [here](https://clang-uml.github.io/md_docs_2jinja__templates.html).

Also checkout [this](https://clang-uml.github.io/md_docs_2test__cases_2t00050.html) test case.
