### ISSUE TITLE
Cannot run it from command line inspite of config file

### ISSUE THREAD

**Issue by rreddy78** [bkryza/clang-uml#230]
Hi,

Sorry for the noob question, but how do I run it with a given config file. Nothing seems to be working:

```
sxv1kor@BANO-C-0012R:~/workspace/maploc/src$ ls .clang-uml
.clang-uml
sxv1kor@BANO-C-0012R:~/workspace/maploc/src$ clang-uml
[error] [tid 274463] [cli_handler.cc:274] Could not open config file .clang-uml: bad file
sxv1kor@BANO-C-0012R:~/workspace/maploc/src$ clang-uml --config .clang-uml
[error] [tid 274638] [cli_handler.cc:274] Could not open config file .clang-uml: bad file

```

**Comment by bkryza** [comment]
@rreddy78 Can you please try:

```shell
clang-uml --validate-only
```

and also paste the contents of your `.clang-uml` config file?

**Comment by rreddy78** [comment]
```
sxv1kor@BANO-C-0012R:~/workspace/maploc/src$ clang-uml --validate-only
[error] [tid 8876] [cli_handler.cc:274] Could not open config file .clang-uml: bad file
```

The contents of my .clang-uml is the example complete config from here: https://clang-uml.github.io/md_docs_2configuration__file.html

The config file create created by --init is working:

```
clang-uml
[info] [tid 9544] [cli_handler.cc:303] Loaded clang-uml config from .clang-uml
[info] [tid 9544] [cli_handler.cc:326] Loading compilation database from /home/sxv1kor/workspace/maploc/src/ directory
[error] [tid 9544] [main.cc:84] Failed to load compilation database from /home/sxv1kor/workspace/maploc/src/ due to: Could not auto-dete


```

**Comment by rreddy78** [comment]
I am able to run it now by modifying the default config file created by --init option. But I am getting these errors now:

```
error: unknown warning option '-Wshadow=compatible-local'; did you mean '-Wshadow-uncaptured-local'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wstrict-null-sentinel' [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Werror,-Wunknown-warning-option]

```

**Comment by bkryza** [comment]
@rreddy78 Please try with the following option:

```shell
clang-uml --query-driver .
```

If this doesn't help, you can remove compile flags not suported by Clang from the compilation database by adding the following config option:

```yaml
remove_compile_flags:
  - -Wshadow=compatible-local
  - -Wstrict-null-sentinel
  - -Wno-maybe-uninitialized
```

**Comment by rreddy78** [comment]
Working fine now after removing many of the compiler flags!

`remove_compile_flags:
  - -Wshadow=compatible-local
  - -Wstrict-null-sentinel
  - -Wno-maybe-uninitialized
  - -Wunused-parameter
  - -Wunused-const-variable
  - -Wunused-but-set-parameter
  - -Wunused-but-set-varia`
