### ISSUE TITLE
Unable to set `query_driver` in `.clang-uml`

### ISSUE THREAD

**Issue by nsgundy** [bkryza/clang-uml#243]
Running `clang-uml` `0.5.0`, I am unable to set `query_driver: 'g++'` in `.clang-uml`. When executing `clang-uml`, the following error is shown:

```
[yaml_decoders.cc:1034] Schema error: /query_driver: undefined node
````

Its referenced here:
https://github.com/bkryza/clang-uml/blob/10dae021e11627bc0eebf7fc72400bde6eaec360/docs/configuration_file.md?plain=1#L21

Seems to be missing from `schema.h`...

**Comment by bkryza** [comment]
@nsgundy Thanks for reporting this. It should now work in latest `master` branch.
