### ISSUE TITLE
Windows Defender Marks 0.5.1 exe Release as Virus

### ISSUE THREAD

**Issue by DeveloperPaul123** [bkryza/clang-uml#254]
Windows defender is pretty convinced that the `0.5.1` release installer contains a virus.

**Comment by bkryza** [comment]
Thanks for the info? Which Windows version is it - on my Windows 10 it installs without any warnings...

**Comment by bkryza** [comment]
Is it possible that it due to the fact that this is unsigned - I don't have any Microsoft developer certificate to sign the Windows binaries...

**Comment by DeveloperPaul123** [comment]
No problem! I haven't had issues with this in the past though, just this latest release. I'm on Windows 11 Pro (23H2 OS Build 22631.3235)

**Comment by DeveloperPaul123** [comment]
Yeah that's what I plan to do. Thanks!
