### ISSUE TITLE
Library Unable to Find yaml-cpp Correctly on Windows (MSVC)

### ISSUE THREAD

**Issue by DeveloperPaul123** [bkryza/clang-uml#255]
I've been following the build instructions here https://github.com/bkryza/clang-uml/blob/master/docs/installation.md#windows-1 for windows and it seems that the latest release (`0.5.1`) doesn't seem to find `yaml-cpp` correctly. 

I had to add the following line to get things working with `yaml` again. 

Lines 109 - 112 of the root CMakeLists.txt

```cmake
elseif(MSVC)
    find_package(yaml-cpp REQUIRED)
    set(YAML_CPP_LIBRARIES "yaml-cpp")
else()
```

Otherwise, it seems the include directory for `yaml` is never set in the case of MSVC builds.

**Comment by bkryza** [comment]
@DeveloperPaul123 Ok, thanks for the info. It did build for me on Windows on my setup, but probably I need to reproduce the steps from scratch, I might have cached some cmake properties already...

**Comment by bkryza** [comment]
@DeveloperPaul123 This is now fixed in `master`.
