### ISSUE TITLE
Build Fails with LLVM 18.x

### ISSUE THREAD

**Issue by DeveloperPaul123** [bkryza/clang-uml#256]
I tried building clang-uml with LLVM `18.1.1` and currently the build is failing. Not sure if it's due to breaking changes in LLVM or if another LLVM sub-project needs to be linked to in LLVMSetup.cmake. 

Currently, getting this include error:

![image](https://github.com/bkryza/clang-uml/assets/6591180/2a44f747-6a6c-4f93-93ab-251e416b2768)
>     Error C1083: Cannot open include file: 'clang/AST/Expr.h': No such file or directory (28, 11)

**Comment by bkryza** [comment]
@DeveloperPaul123 First of all, are you sure you're building with the latest master? I've introduced support for LLVM 18 a day after releasing 0.5.1 :-)

Also, I haven't checked if it works with LLVM 18 on Windows, only on Linux. If you get this error with latest `master` branch of `clang-uml`, I will investigate...

**Comment by DeveloperPaul123** [comment]
@bkryza Oh! I didn't see that. I've been using the latest tagged release, not master. I'll check the things you mentioned and update this issue.

**Comment by DeveloperPaul123** [comment]
Ok I tried building with master and things still fail. I confirmed that the missing includes do in fact exist on disk

![image](https://github.com/bkryza/clang-uml/assets/6591180/6b6219a4-40a9-4df3-9717-acde3ab4102a)

> CMake is re-running because F:/Repositories/clang-uml/build/CMakeFiles/generate.stamp is out-of-date.
  the file 'F:/Repositories/clang-uml/dependencies/install/lib/cmake/llvm/AddLLVM.cmake'
  is newer than 'F:/Repositories/clang-uml/build/CMakeFiles/generate.stamp.depend'
  result='-1'
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- clang-uml version: 0.5.1-3-g0fac87c
-- Checking for LLVM and Clang...
-- Found LLVM 18.1.1
-- Using LLVMConfig.cmake from: F:/Repositories/clang-uml/dependencies/install/lib/cmake/llvm
-- LLVM library dir: F:/Repositories/clang-uml/dependencies/install/lib
-- Found LibTooling libraries: clangLex;clangFrontend;clangSerialization;clangDriver;clangParse;clangSema;clangSupport;clangAnalysis;clangAST;clangBasic;clangEdit;clangLex;clangTooling;LLVMipo;LLVMScalarOpts;LLVMInstCombine;LLVMTransformUtils;LLVMAnalysis;LLVMTarget;LLVMOption;LLVMMCParser;LLVMMC;LLVMObject;LLVMBitReader;LLVMCore;LLVMSupport;LLVMWindowsDriver;LLVMWindowsManifest;clangASTMatchers
-- Checking for yaml-cpp...
-- Found yaml-cpp libraries: yaml-cpp
-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: F:/Repositories/clang-uml/build
MSBuild version 17.9.5+33de0b227 for .NET Framework
class_diagram_generator.cc
F:\Repositories\clang-uml\src\common\clang_utils.h(27,10): error C1083: Cannot open include file: 'clang/AST/Expr.h': No such file or directory [F:\Repositories\clang-uml\build\src\clang-umllib.vcxproj]  (compiling source file '../../src/class_diagram/generators/json/class_diagram_generator.cc')

**Comment by bkryza** [comment]
@DeveloperPaul123 I've rebuilt my MSVC setup from scratch using LLVM 18.1.1 and I did not encounter this issue - there was another one during linking but I've fixed it in `master` branch now. 

Is it possible that somehow during compilation of `clang-uml` in your environment the LLVM Clang include directory is not included in the compilation flags?

**Comment by DeveloperPaul123** [comment]
@bkryza Ok I'll give this a try again from scratch and see if I can reproduce it again. 

It's possible I suppose but I'm not sure how that would be possible.

**Comment by DeveloperPaul123** [comment]
I was making a mistake on the command line and `clang` was not being built as part of LLVM 🤦 Sorry for the noise
