### ISSUE TITLE
Add Mermaid diagram generators

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#27]
Add at least basic support for generation of Mermaid (https://mermaid-js.github.io) diagrams in addition to PlantUML...

**Comment by DeveloperPaul123** [comment]
This would be very useful for us to keep diagrams in markdown documentation automatically up to date

**Comment by bkryza** [comment]
This is currently on hold due to too limited template class rendering (called in Mermaid `generictype`) for instance the following code:

```
classDiagram

class A~T~ {
    +T value
}

class A~T,N~ {
    
}

class A~int~ {
    
}
```

renders the following diagram:

```mermaid
classDiagram

class A~T~ {
    +T value
}

class A~T,N~ {
    
}

class A~int~ {
    
}

A~int~ <|.. A~T~
```

with only `class A<T>`...

**Comment by DeveloperPaul123** [comment]
That's a shame. Seems like there is an open issue for mermaid regarding this https://github.com/mermaid-js/mermaid/issues/3287 ? But no movement sadly.

**Comment by DeveloperPaul123** [comment]
@bkryza Even with the limitation for class templates, would it still be worth pursuing this so that diagrams can be generated for non-template code?

**Comment by bkryza** [comment]
@DeveloperPaul123 Personally to me it's not worth it as this is very serious limitation and the effort related to developing it and even more so on maintaining it is just too big. However, if Mermaid finally supports them then I will definitely reconsider!

Also, if you're really pressed to have diagrams in Mermaid format, please note that `clang-uml` now has a JSON generator, which basically dumps it's internal diagram model in JSON format (simply add `-g json` to command line), which should be relatively trivial to convert to any other format using some Python script. Examples of the output are in the test cases, e.g.:

https://github.com/bkryza/clang-uml/blob/master/docs/test_cases/t00002.md#generated-json-models

**Comment by DeveloperPaul123** [comment]
@bkryza That seems reasonable; and thanks for the tip regarding `JSON` output, I missed that part of the docs. We can look into pursuing that. 

How stable is the JSON output format at this point?

**Comment by bkryza** [comment]
@DeveloperPaul123 This is a good question :-) On the one hand I'd like to think that at least the overall structure of the JSON is stable, as I already have substantial amount of test cases for it, but on the other hand it is a very new feature so it also depends on the feedback I get on it...

**Comment by DeveloperPaul123** [comment]
@bkryza That seems reasonable. In the short term, until feedback is received, would it be possible to add a `version` parameter to indicate the schema version?

**Comment by bkryza** [comment]
@DeveloperPaul123 The latest version (0.3.4) now contains by default the following JSON element:

```yaml
  "metadata": {
    "clang_uml_version": "0.3.4",
    "llvm_version": "Ubuntu clang version 15.0.6",
    "schema_version": 1
  },
```

**Comment by DeveloperPaul123** [comment]
@bkryza Awesome, thanks for adding that!

**Comment by mahatt** [comment]
Hi @bkryza , mermaid layout looks quite lot like dot, with dot engine layout. I was trying to convert json to dot and render, had success with less than 15 class nodes. I am curious what are lucrative features from mermaid ?

**Comment by DeveloperPaul123** [comment]
It looks like mermaid has potentially fixed issues with template types. They have a PR that has been merged. 

See https://github.com/mermaid-js/mermaid/issues/3287#event-10265432344 and https://github.com/mermaid-js/mermaid/issues/4565

**Comment by bkryza** [comment]
@DeveloperPaul123 I've deployed locally their latest `develop` branch but unfortunately it still doesn't support properly template specializations, however the good news is I found a way (though a bit convoluted) to actually get it to render template specializations:

```
classDiagram
    class A001["A&lt;T>"] {
    }
    class A002["A&lt;int>"] {
    }
    class A003["A&lt;std::function(int,std::string)>"] {
    }
    A001 <|.. A002
    A002 <|.. A003
```

```mermaid
classDiagram
    class A001["A&lt;T>"] {
    }
    class A002["A&lt;int>"] {
    }
    class A003["A&lt;std::function(int,std::string)>"] {
    }
    A001 <|.. A002
    A002 <|.. A003
```

In a nutshell, I can just generate class names based on unique identifiers in my model, and then generate the actual class label and use the unique class names for relationships.
The tricky part here was to figure out to use `&lt;` for left angle bracket because for some reason otherwise there is a parse error in javascript console in the browser.

The question is whether you care about how the actual diagram source code looks like - or are you just interested in the output diagram?

Anyway with this, I'll definitely revisit the MermaidJS generator, maybe even for the next release...

**Comment by DeveloperPaul123** [comment]
@bkryza Thanks for the update!

For me personally I would say that we care more about the generated diagram, and not so much what the diagram source code looks like.

**Comment by bkryza** [comment]
@DeveloperPaul123 Latest release 0.4.0 now contains support for MermaidJS for all types of diagrams supported already for PlantUML (just add `-g mermaid` in command line options). I've tried to keep as many of the PlantUML features as possible in the mermaid generator but there are some differences (e.g. missing packages/namespaces option in class diagrams).

You can browse through [test cases documentation](https://clang-uml.github.io/md_docs_2test__cases.html) to compare PlantUML and Mermaid diagrams generates from the same code snippets.

If you'll have any specific issues with Mermaid generator please open new issue...

**Comment by DeveloperPaul123** [comment]
@bkryza This is amazing! Thanks for the update. I'll be sure to give this a try on some of our projects. Thanks again
