### ISSUE TITLE
0.5.4 release did not get completed

### ISSUE THREAD

**Issue by chenrui333** [bkryza/clang-uml#308]
👋 looks like 0.5.4 release was not completed, ie did not get marked as latest release. Raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/181369

**Comment by bkryza** [comment]
@chenrui333 Thanks, I'm still building packages for Ubuntu and Windows, I'll mark it latest when I have all packages, hopefully later today...

**Comment by chenrui333** [comment]
got it, thanks! :)
