### ISSUE TITLE
Braces in default arguments break mermaid diagrams

### ISSUE THREAD

**Issue by sthlm58** [bkryza/clang-uml#312]
If you generate a mermaid diagram from the following code
```
class Foo {
public:
    Foo(void* parent = {}) {}
};

int main() {}
```

You get the following mermaid:
```
classDiagram
    class C_0017490737515057045975["Foo"]
    class C_0017490737515057045975 {
        +Foo(void * parent = {}) : void
    }
```

That is invalid with:
```
Diagram syntax error

Error: Error: Parse error on line 4:
...Foo(void * parent = {}) : void }
-----------------------^
Expecting 'STRUCT_STOP', 'MEMBER', got 'OPEN_IN_STRUCT'
```

I'm not sure if those `{` and `}` characters can be escaped...

**Comment by bkryza** [comment]
@sthlm58 Thanks for reporting this. It should now be fixed in `master` branch. I've added a [test](https://github.com/bkryza/clang-uml/blob/master/docs/test_cases/t00003.md) for this - see the `default_int_braces` method...
