### ISSUE TITLE
Failed to find yaml-cpp library!

### ISSUE THREAD

**Issue by kingjane** [bkryza/clang-uml#323]
On my Mac with an M2 chip, I encountered an error when building from source using the  `make release` command:

> -- Checking for yaml-cpp...
-- Checking for module 'yaml-cpp'
--   No package 'yaml-cpp' found
CMake Error at CMakeLists.txt:157 (message):
  Failed to find yaml-cpp library!

In clang-uml/CMakeLists.txt:142, changing "YAML_CPP_LIBRARY" to "YAML_CPP_LIBRARIES" resolved the issue, and the build succeeded. I suspect this is a typo.

**Comment by bkryza** [comment]
@kingjane Thanks for reporting this. On my Mac Mini M2 it works as it is:

```
...

-- Checking for yaml-cpp...
-- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2")
-- Checking for module 'yaml-cpp'
--   Found yaml-cpp, version 0.8.0
-- Found yaml-cpp libraries: yaml-cpp

...

$ brew info yaml-cpp
==> yaml-cpp: stable 0.8.0 (bottled)
C++ YAML parser and emitter for YAML 1.2 spec
https://github.com/jbeder/yaml-cpp
Installed
/opt/homebrew/Cellar/yaml-cpp/0.8.0 (50 files, 465.9KB) *
  Poured from bottle using the formulae.brew.sh API on 2024-07-18 at 23:59:06
...
```

Is your `yaml-cpp` installed through Homebrew or otherwise?

**Comment by kingjane** [comment]
@bkryza 
Yes, I installed `yaml-cpp` via Homebrew. 
It's a bit strange that it works fine on your Mac. The `YAML_CPP_LIBRARIES` might have been set somewhere else.

**Comment by bkryza** [comment]
@kingjane Could you possibly send me the output of the following command (but clear your build directory first e.g. using `make clean`):

```
$ cmake -S . -B debug -DCMAKE_PREFIX=/opt/homebrew/opt/llvm/lib/cmake/llvm -LAH | grep YAML
```

In my case it produces the following - 
```                                                                              
YAML_CPP_INCLUDE_DIR:PATH=/opt/homebrew/include
YAML_CPP_LIBRARY:FILEPATH=/opt/homebrew/lib/libyaml-cpp.dylib
pkgcfg_lib_YAML_CPP_yaml-cpp:FILEPATH=/opt/homebrew/Cellar/yaml-cpp/0.8.0/lib/libyaml-cpp.dylib
```

**Comment by kingjane** [comment]
@bkryza The output on my end is:
```
YAML_CPP_INCLUDE_DIR:PATH=/opt/homebrew/include
YAML_CPP_LIBRARIES:FILEPATH=/opt/homebrew/lib/libyaml-cpp.dylib
```

**Comment by bkryza** [comment]
@kingjane Thanks! I'll have to investigate this...

**Comment by bkryza** [comment]
@kingjane I've refactored the CMake logic for detecting yaml-cpp on macos and in fact it was not necessary anymore as simple `find_package(yaml-cpp)` just works now. Thanks again for reporting this...
