### ISSUE TITLE
Blocking build

### ISSUE THREAD

**Issue by nicolo011** [bkryza/clang-uml#35]
The build of master branch from a fresh ubuntu install blocks the machine, while building variable_parser.cpp.o
I have no other message than the one below.

cmake -S . -B release \
	-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
	-DCMAKE_BUILD_TYPE=Release \
	-DLLVM_CONFIG_PATH=
-- Checking for fmt...
-- Checking for spdlog...
-- Checking for yaml-cpp...
-- Checking for libclang...
-- llvm-config executable found: /usr/bin/llvm-config-12
-- Using CMAKE_CXX_FLAGS:  -std=c++17 -I/usr/lib/llvm-12/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Installing type_safe via submodule
-- Installing debug_assert via submodule
-- Installing tiny-process-library via submodule
-- Found llvm-config at /usr/bin/llvm-config-12
-- Using LLVM version 12.0.1
-- Found libclang header files at /usr/lib/llvm-12/include
-- Found libclang library at /usr/lib/llvm-12/lib/libclang.so
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- FOUND GCC STDDEF INCLUDE /usr/lib/gcc/x86_64-linux-gnu/11/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nicolas/clang-uml/release
make -C release -j
make[1] : on entre dans le répertoire « /home/nicolas/clang-uml/release »
make[2] : on entre dans le répertoire « /home/nicolas/clang-uml/release »
make[3] : on entre dans le répertoire « /home/nicolas/clang-uml/release »
make[3] : on entre dans le répertoire « /home/nicolas/clang-uml/release »
make[3] : on quitte le répertoire « /home/nicolas/clang-uml/release »
make[3] : on quitte le répertoire « /home/nicolas/clang-uml/release »
[  1%] Built target _cppast_tiny_process
make[3] : on entre dans le répertoire « /home/nicolas/clang-uml/release »
[  2%] Building CXX object CMakeFiles/clang-umllib.dir/src/class_diagram/model/class.cc.o
make[3] : on entre dans le répertoire « /home/nicolas/clang-uml/release »
[  3%] Building CXX object CMakeFiles/clang-umllib.dir/src/class_diagram/generators/plantuml/class_diagram_generator.cc.o
[  4%] Building CXX object CMakeFiles/clang-umllib.dir/src/class_diagram/model/class_member.cc.o
[  4%] Building CXX object CMakeFiles/clang-umllib.dir/src/class_diagram/model/class_method.cc.o
[  4%] Building CXX object CMakeFiles/clang-umllib.dir/src/class_diagram/model/diagram.cc.o
[  4%] Building CXX object CMakeFiles/clang-umllib.dir/src/class_diagram/model/class_element.cc.o
[  5%] Building CXX object CMakeFiles/clang-umllib.dir/src/class_diagram/model/class_template.cc.o
make[3] : on quitte le répertoire « /home/nicolas/clang-uml/release »
[  6%] Building CXX object CMakeFiles/clang-umllib.dir/src/class_diagram/model/enum.cc.o
[  6%] Building CXX object CMakeFiles/clang-umllib.dir/src/class_diagram/model/method_parameter.cc.o
[  6%] Building CXX object CMakeFiles/clang-umllib.dir/src/class_diagram/visitor/translation_unit_context.cc.o
make[3] : on entre dans le répertoire « /home/nicolas/clang-uml/release »
[  7%] Building CXX object CMakeFiles/clang-umllib.dir/src/class_diagram/visitor/element_visitor_context.cc.o
[  8%] Building CXX object CMakeFiles/clang-umllib.dir/src/class_diagram/visitor/translation_unit_visitor.cc.o
[  8%] Building CXX object CMakeFiles/clang-umllib.dir/src/common/generators/plantuml/generator.cc.o
[  8%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_alias_template.cpp.o
[  9%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/code_generator.cpp.o
[ 10%] Building CXX object CMakeFiles/clang-umllib.dir/src/common/model/decorated_element.cc.o
[ 11%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_attribute.cpp.o
[ 11%] Building CXX object CMakeFiles/clang-umllib.dir/src/common/model/diagram_element.cc.o
[ 12%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_class_template.cpp.o
[ 13%] Building CXX object CMakeFiles/clang-umllib.dir/src/common/model/diagram.cc.o
[ 13%] Building CXX object CMakeFiles/clang-umllib.dir/src/common/model/element.cc.o
[ 14%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_entity.cpp.o
[ 15%] Building CXX object CMakeFiles/clang-umllib.dir/src/common/model/diagram_filter.cc.o
[ 15%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_class.cpp.o
[ 15%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_entity_index.cpp.o
[ 15%] Building CXX object CMakeFiles/clang-umllib.dir/src/common/model/package.cc.o
[ 15%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_enum.cpp.o
[ 16%] Building CXX object CMakeFiles/clang-umllib.dir/src/common/model/namespace.cc.o
[ 17%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_expression.cpp.o
[ 18%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_file.cpp.o
[ 19%] Building CXX object CMakeFiles/clang-umllib.dir/src/common/model/relationship.cc.o
[ 19%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_function.cpp.o
[ 19%] Building CXX object CMakeFiles/clang-umllib.dir/src/config/config.cc.o
[ 19%] Building CXX object CMakeFiles/clang-umllib.dir/src/common/model/source_file.cc.o
[ 19%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_forward_declarable.cpp.o
[ 20%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_friend.cpp.o
[ 21%] Building CXX object CMakeFiles/clang-umllib.dir/src/cx/util.cc.o
[ 21%] Building CXX object CMakeFiles/clang-umllib.dir/src/decorators/decorators.cc.o
[ 22%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_language_linkage.cpp.o
[ 23%] Building CXX object CMakeFiles/clang-umllib.dir/src/include_diagram/generators/plantuml/include_diagram_generator.cc.o
[ 24%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_function_template.cpp.o
[ 25%] Building CXX object CMakeFiles/clang-umllib.dir/src/include_diagram/model/diagram.cc.o
[ 25%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_member_function.cpp.o
[ 26%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_member_variable.cpp.o
[ 27%] Building CXX object CMakeFiles/clang-umllib.dir/src/include_diagram/visitor/element_visitor_context.cc.o
[ 27%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_namespace.cpp.o
[ 28%] Building CXX object CMakeFiles/clang-umllib.dir/src/include_diagram/visitor/translation_unit_visitor.cc.o
[ 28%] Building CXX object CMakeFiles/clang-umllib.dir/src/include_diagram/visitor/translation_unit_context.cc.o
[ 28%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_template_parameter.cpp.o
[ 29%] Building CXX object CMakeFiles/clang-umllib.dir/src/package_diagram/generators/plantuml/package_diagram_generator.cc.o
[ 30%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_static_assert.cpp.o
[ 31%] Building CXX object CMakeFiles/clang-umllib.dir/src/package_diagram/model/diagram.cc.o
[ 32%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_preprocessor.cpp.o
[ 32%] Building CXX object CMakeFiles/clang-umllib.dir/src/package_diagram/visitor/translation_unit_context.cc.o
[ 32%] Building CXX object CMakeFiles/clang-umllib.dir/src/package_diagram/visitor/element_visitor_context.cc.o
[ 32%] Building CXX object CMakeFiles/clang-umllib.dir/src/package_diagram/visitor/translation_unit_visitor.cc.o
[ 33%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_token.cpp.o
[ 34%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_type_alias.cpp.o
[ 34%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_type.cpp.o
[ 35%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_variable.cpp.o
[ 35%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/cpp_variable_template.cpp.o
[ 36%] Building CXX object CMakeFiles/clang-umllib.dir/src/sequence_diagram/generators/plantuml/sequence_diagram_generator.cc.o
[ 37%] Building CXX object CMakeFiles/clang-umllib.dir/src/sequence_diagram/model/diagram.cc.o
[ 37%] Building CXX object CMakeFiles/clang-umllib.dir/src/sequence_diagram/visitor/translation_unit_context.cc.o
[ 38%] Building CXX object CMakeFiles/clang-umllib.dir/src/sequence_diagram/visitor/translation_unit_visitor.cc.o
[ 39%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/diagnostic_logger.cpp.o
[ 39%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/visitor.cpp.o
[ 40%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/cxtokenizer.cpp.o
[ 41%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/class_parser.cpp.o
[ 42%] Building CXX object CMakeFiles/clang-umllib.dir/src/util/util.cc.o
[ 42%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/debug_helper.cpp.o
[ 42%] Building CXX object CMakeFiles/clang-umllib.dir/src/util/thread_pool_executor.cc.o
[ 42%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/expression_parser.cpp.o
[ 43%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/friend_parser.cpp.o
[ 43%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/function_parser.cpp.o
[ 44%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/enum_parser.cpp.o
[ 45%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/libclang_parser.cpp.o
[ 46%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/language_linkage_parser.cpp.o
[ 47%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/parse_functions.cpp.o
[ 47%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/namespace_parser.cpp.o
[ 47%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/preprocessor.cpp.o
[ 48%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/type_parser.cpp.o
[ 49%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/template_parser.cpp.o
[ 49%] Building CXX object thirdparty/cppast/src/CMakeFiles/cppast.dir/libclang/variable_parser.cpp.o

**Comment by bkryza** [comment]
@nicolo011 This typically happens with GCC when you have too little free memory for the compilation with maximum number of cores, please retry with:

`make -C release -j2`
