### ISSUE TITLE
Compilation failed: clang-c/CXCompilationDatabase.h: No such file or directory

### ISSUE THREAD

**Issue by YeusepeScholar** [bkryza/clang-uml#37]
When I go and compile the program, I get the following error:
uml/src/class_diagram/visitor/translation_unit_context.cc:21:
/home/yeusepe/Documents/AutoC++/clang-uml/src/cx/util.h:22:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   22 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:238: CMakeFiles/clang-umllib.dir/src/class_diagram/visitor/translation_unit_context.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/cx/util.cc:19:
/home/yeusepe/Documents/AutoC++/clang-uml/src/cx/util.h:22:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   22 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:446: CMakeFiles/clang-umllib.dir/src/cx/util.cc.o] Error 1
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/common/model/diagram_filter.h:26,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/common/model/diagram_filter.cc:19:
/home/yeusepe/Documents/AutoC++/clang-uml/src/cx/util.h:22:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   22 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:316: CMakeFiles/clang-umllib.dir/src/common/model/diagram_filter.cc.o] Error 1
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/class_diagram/visitor/translation_unit_visitor.cc:19:
/home/yeusepe/Documents/AutoC++/clang-uml/src/class_diagram/visitor/translation_unit_visitor.h:24:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   24 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/common/model/diagram_filter.h:26,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/common/generators/plantuml/generator.h:20,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/include_diagram/generators/plantuml/include_diagram_generator.h:20,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/include_diagram/generators/plantuml/include_diagram_generator.cc:19:
/home/yeusepe/Documents/AutoC++/clang-uml/src/cx/util.h:22:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   22 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:251: CMakeFiles/clang-umllib.dir/src/class_diagram/visitor/translation_unit_visitor.cc.o] Error 1
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:472: CMakeFiles/clang-umllib.dir/src/include_diagram/generators/plantuml/include_diagram_generator.cc.o] Error 1
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/common/model/diagram_filter.h:26,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/common/generators/plantuml/generator.h:20,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/common/generators/plantuml/generator.cc:18:
/home/yeusepe/Documents/AutoC++/clang-uml/src/cx/util.h:22:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   22 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:264: CMakeFiles/clang-umllib.dir/src/common/generators/plantuml/generator.cc.o] Error 1
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/class_diagram/generators/plantuml/class_diagram_generator.h:23,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/class_diagram/generators/plantuml/class_diagram_generator.cc:19:
/home/yeusepe/Documents/AutoC++/clang-uml/src/class_diagram/visitor/translation_unit_visitor.h:24:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   24 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:82: CMakeFiles/clang-umllib.dir/src/class_diagram/generators/plantuml/class_diagram_generator.cc.o] Error 1
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/common/model/diagram_filter.h:26,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/common/generators/plantuml/generator.h:20,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/package_diagram/generators/plantuml/package_diagram_generator.h:20,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/package_diagram/generators/plantuml/package_diagram_generator.cc:19:
/home/yeusepe/Documents/AutoC++/clang-uml/src/cx/util.h:22:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   22 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:537: CMakeFiles/clang-umllib.dir/src/package_diagram/generators/plantuml/package_diagram_generator.cc.o] Error 1
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/common/model/diagram_filter.h:26,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/common/model/diagram.cc:21:
/home/yeusepe/Documents/AutoC++/clang-uml/src/cx/util.h:22:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   22 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:290: CMakeFiles/clang-umllib.dir/src/common/model/diagram.cc.o] Error 1
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/include_diagram/visitor/translation_unit_context.cc:21:
/home/yeusepe/Documents/AutoC++/clang-uml/src/cx/util.h:22:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   22 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/yeusepe/Documents/AutoC++/clang-uml/src/sequence_diagram/visitor/translation_unit_context.cc:21:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   21 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:511: CMakeFiles/clang-umllib.dir/src/include_diagram/visitor/translation_unit_context.cc.o] Error 1
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:654: CMakeFiles/clang-umllib.dir/src/sequence_diagram/visitor/translation_unit_context.cc.o] Error 1
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/common/model/diagram_filter.h:26,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/common/generators/plantuml/generator.h:20,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/sequence_diagram/generators/plantuml/sequence_diagram_generator.h:20,
                 from /home/yeusepe/Documents/AutoC++/clang-uml/src/sequence_diagram/generators/plantuml/sequence_diagram_generator.cc:19:
/home/yeusepe/Documents/AutoC++/clang-uml/src/cx/util.h:22:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   22 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:602: CMakeFiles/clang-umllib.dir/src/sequence_diagram/generators/plantuml/sequence_diagram_generator.cc.o] Error 1
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/sequence_diagram/visitor/translation_unit_visitor.cc:22:
/home/yeusepe/Documents/AutoC++/clang-uml/src/cx/util.h:22:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   22 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:667: CMakeFiles/clang-umllib.dir/src/sequence_diagram/visitor/translation_unit_visitor.cc.o] Error 1
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/package_diagram/visitor/translation_unit_visitor.cc:19:
/home/yeusepe/Documents/AutoC++/clang-uml/src/package_diagram/visitor/translation_unit_visitor.h:24:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   24 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:589: CMakeFiles/clang-umllib.dir/src/package_diagram/visitor/translation_unit_visitor.cc.o] Error 1
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/package_diagram/visitor/translation_unit_context.cc:21:
/home/yeusepe/Documents/AutoC++/clang-uml/src/cx/util.h:22:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   22 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:576: CMakeFiles/clang-umllib.dir/src/package_diagram/visitor/translation_unit_context.cc.o] Error 1
In file included from /home/yeusepe/Documents/AutoC++/clang-uml/src/include_diagram/visitor/translation_unit_visitor.cc:19:
/home/yeusepe/Documents/AutoC++/clang-uml/src/include_diagram/visitor/translation_unit_visitor.h:26:10: fatal error: clang-c/CXCompilationDatabase.h: No such file or directory
   26 | #include <clang-c/CXCompilationDatabase.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/clang-umllib.dir/build.make:524: CMakeFiles/clang-umllib.dir/src/include_diagram/visitor/translation_unit_visitor.cc.o] Error 1
make[3]: Leaving directory '/home/yeusepe/Documents/AutoC++/clang-uml/release'
make[2]: *** [CMakeFiles/Makefile2:238: CMakeFiles/clang-umllib.dir/all] Error 2
make[2]: Leaving directory '/home/yeusepe/Documents/AutoC++/clang-uml/release'
make[1]: *** [Makefile:160: all] Error 2
make[1]: Leaving directory '/home/yeusepe/Documents/AutoC++/clang-uml/release'
make: *** [Makefile:50: release] Error 2

**Comment by bkryza** [comment]
@YeusepeScholar please make sure you have all the required dependencies installed: https://github.com/bkryza/clang-uml#building-from-source - if yes, please describe your environment in more detail and the commands you're using to compile, I will try to reproduce...
