### ISSUE TITLE
Warnings (as errors) when building clang-uml with clang 14

### ISSUE THREAD

**Issue by meastp** [bkryza/clang-uml#48]
These errors fails the build:

```
[ 67%] Building CXX object tests/CMakeFiles/test_cases.dir/t00007/t00007.cc.o
/mnt/c/Users/mattar/source/repos/geodatamod/clang-uml-master/tests/t00003/t00003.cc:52:9: error: private field 'a' is not used [-Werror,-Wunused-private-field]
    int a, b, c;
        ^
/mnt/c/Users/mattar/source/repos/geodatamod/clang-uml-master/tests/t00003/t00003.cc:52:12: error: private field 'b' is not used [-Werror,-Wunused-private-field]
    int a, b, c;
           ^
/mnt/c/Users/mattar/source/repos/geodatamod/clang-uml-master/tests/t00003/t00003.cc:52:15: error: private field 'c' is not used [-Werror,-Wunused-private-field]
    int a, b, c;
              ^
3 errors generated.
make[3]: *** [tests/CMakeFiles/test_cases.dir/build.make:104: tests/CMakeFiles/test_cases.dir/t00003/t00003.cc.o] Error 1
```

**Comment by bkryza** [comment]
@meastp Thanks for the issue - can you add `-Wno-unused-private-field` here [https://github.com/bkryza/clang-uml/blob/master/tests/CMakeLists.txt#L7](https://github.com/bkryza/clang-uml/blob/master/tests/CMakeLists.txt#L7) and check if it helps?

In general test cases have less restrictive warnings - unfortunately there are big inconsistencies between gcc, clang and even their different versions in which warnings are reported and when...

**Comment by meastp** [comment]
@bkryza Yes, this fixed the warnings, thanks :)

**Comment by bkryza** [comment]
@meastp I've noticed at least on my system it does fix compilation errors with clang, but when I run `make test` several test cases fail - for some reason some member fields with templates are reported by libclang as `int` - so please check first if all test cases pass on your system - if not - try building `clang-uml` with GCC, at the moment I don't know what could be the reason for this...

**Comment by meastp** [comment]
@bkryza I'm just using `make release` for now, and it works (with clang 14 on ubuntu 22.04)
