### ISSUE TITLE
Building error fix needed .

### ISSUE THREAD

**Issue by equilibrium-liberalism** [bkryza/clang-uml#67]
:clang-uml $ make release
cmake -S . -B release \
		-DGIT_VERSION=0.3.0-2-g476a787 \
		-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_CXX_FLAGS="" \
		-DCMAKE_EXE_LINKER_FLAGS="" \
        -DLLVM_VERSION=
-- Checking for LLVM and Clang...
-- Found LLVM 15.0.6
-- Using LLVMConfig.cmake in: /usr/local/Cellar/llvm/15.0.6/lib/cmake/llvm
-- LLVM library dir: /usr/local/Cellar/llvm/15.0.6/lib
-- Checking for yaml-cpp...
-- Using CMAKE_CXX_FLAGS:  -Werror -Wall -Wextra -std=c++17 -Wno-unused-parameter -Wno-unused-private-field
t00002/.clang-uml
t00003/.clang-uml
t00004/.clang-uml
t00005/.clang-uml
t00006/.clang-uml
t00007/.clang-uml
t00008/.clang-uml
t00009/.clang-uml
t00010/.clang-uml
t00011/.clang-uml
t00012/.clang-uml
t00013/.clang-uml
t00014/.clang-uml
t00015/.clang-uml
t00016/.clang-uml
t00017/.clang-uml
t00018/.clang-uml
t00019/.clang-uml
t00020/.clang-uml
t00021/.clang-uml
t00022/.clang-uml
t00023/.clang-uml
t00024/.clang-uml
t00025/.clang-uml
t00026/.clang-uml
t00027/.clang-uml
t00028/.clang-uml
t00029/.clang-uml
t00030/.clang-uml
t00031/.clang-uml
t00032/.clang-uml
t00033/.clang-uml
t00034/.clang-uml
t00035/.clang-uml
t00036/.clang-uml
t00037/.clang-uml
t00038/.clang-uml
t00039/.clang-uml
t00040/.clang-uml
t00041/.clang-uml
t00042/.clang-uml
t00043/.clang-uml
t00044/.clang-uml
t00045/.clang-uml
t00046/.clang-uml
t00047/.clang-uml
t00048/.clang-uml
t00049/.clang-uml
t00050/.clang-uml
t20001/.clang-uml
t20002/.clang-uml
t20003/.clang-uml
t20004/.clang-uml
t20005/.clang-uml
t20006/.clang-uml
t20007/.clang-uml
t20008/.clang-uml
t20009/.clang-uml
t20010/.clang-uml
t20011/.clang-uml
t20012/.clang-uml
t20013/.clang-uml
t20014/.clang-uml
t20015/.clang-uml
t20016/.clang-uml
t20017/.clang-uml
t20018/.clang-uml
t20019/.clang-uml
t20020/.clang-uml
t20021/.clang-uml
t20022/.clang-uml
t20023/.clang-uml
t20024/.clang-uml
t20025/.clang-uml
t20026/.clang-uml
t20027/.clang-uml
t20028/.clang-uml
t20029/.clang-uml
t30001/.clang-uml
t30002/.clang-uml
t30003/.clang-uml
t30004/.clang-uml
t30005/.clang-uml
t30006/.clang-uml
t30007/.clang-uml
t30008/.clang-uml
t40001/.clang-uml
t40002/.clang-uml
t40003/.clang-uml
t90000/.clang-uml
test_config_data/filters.yml
test_config_data/includes.yml
test_config_data/includes1.yml
test_config_data/includes2.yml
test_config_data/inherited.yml
test_config_data/layout.yml
test_config_data/simple.yml
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/***/Documents/GitHub/clang-uml/release
make -C release -j4
[ 29%] Built target clang-umllib
[ 29%] Building CXX object tests/CMakeFiles/test_model.dir/test_model.cc.o
[ 30%] Building CXX object tests/CMakeFiles/test_util.dir/test_util.cc.o
[ 31%] Building CXX object tests/CMakeFiles/test_decorator_parser.dir/test_decorator_parser.cc.o
[ 32%] Built target clang-uml
[ 33%] Building CXX object tests/CMakeFiles/test_config.dir/test_config.cc.o
error: unknown warning option '-Wno-aggressive-loop-optimizations' [-Werror,-Wunknown-warning-option]
make[3]: *** [tests/CMakeFiles/test_decorator_parser.dir/test_decorator_parser.cc.o] Error 1
make[2]: *** [tests/CMakeFiles/test_decorator_parser.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
error: unknown warning option '-Wno-aggressive-loop-optimizations' [-Werror,-Wunknown-warning-option]
make[3]: *** [tests/CMakeFiles/test_model.dir/test_model.cc.o] Error 1
make[2]: *** [tests/CMakeFiles/test_model.dir/all] Error 2
error: unknown warning option '-Wno-aggressive-loop-optimizations' [-Werror,-Wunknown-warning-option]
make[3]: *** [tests/CMakeFiles/test_util.dir/test_util.cc.o] Error 1
make[2]: *** [tests/CMakeFiles/test_util.dir/all] Error 2
error: unknown warning option '-Wno-aggressive-loop-optimizations' [-Werror,-Wunknown-warning-option]
make[3]: *** [tests/CMakeFiles/test_config.dir/test_config.cc.o] Error 1
make[2]: *** [tests/CMakeFiles/test_config.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [release] Error 2

**Comment by equilibrium-liberalism** [comment]
**use follwing cmake file will  fix the above issuse.**

cmake_minimum_required(VERSION 3.12)

#
# Project name
#
project(clang-uml)

#
# CMake standard defines
#
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_COMPILER /usr/local/Cellar/llvm/15.0.6/bin/clang++ CACHE FILEPATH "Path to C++ compiler")

set(CMAKE_VERBOSE_MAKEFILE OFF)
set(CMAKE_FIND_DEBUG_MODE OFF)
if(APPLE)
    set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES})
endif(APPLE)

#
# clang-uml custom defines
#
set(CLANG_UML_INSTALL_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/include)
set(CLANG_UML_INSTALL_BIN_DIR ${PROJECT_SOURCE_DIR}/bin)
set(UML_HEADERS_DIR ${PROJECT_SOURCE_DIR}/src/uml)

#
# CMake build options
#
option(LINK_LLVM_SHARED "Should LLVM be linked using shared libraries or statically" ON)
#set(LLVM_CONFIG_EXECUTABLE "/usr/local/Cellar/llvm/15.0.6/lib/cmake/llvm" CACHE FILEPATH "Path to custom llvm-config executable")
set(LLVM_VERSION CACHE STRING "Path to custom llvm-config executable")
set(GIT_VERSION "0.3.0" CACHE STRING "clang-uml version")

#export CXX=/usr/local/Cellar/llvm/15.0.6/bin/clang++



#
# Setup LLVM
#
message(STATUS "Checking for LLVM and Clang...")
if(LLVM_PREFIX)
    message(STATUS "Using llvm-config from ${LLVM_CONFIG_PATH}")
    set(LIBCLANG_LLVM_CONFIG_EXECUTABLE ${LLVM_CONFIG_PATH})
    set(LLVM_CONFIG_BINARY ${LLVM_CONFIG_PATH})
endif(LLVM_PREFIX)

find_package(LLVM ${LLVM_VERSION} CONFIG REQUIRED)

list(APPEND CMAKE_MODULE_PATH ${LLVM_DIR})
include(AddLLVM)

message(STATUS "Found LLVM ${LLVM_PACKAGE_VERSION}")
message(STATUS "Using LLVMConfig.cmake in: ${LLVM_DIR}")
message(STATUS "LLVM library dir: ${LLVM_LIBRARY_DIR}")

if(LINK_LLVM_SHARED)
    set(LIBTOOLING_LIBS clang-cpp LLVM)
else(LINK_LLVM_SHARED)
    set(LIBTOOLING_LIBS
        clangLex
        clangFrontend
        clangSerialization
        clangDriver
        clangParse
        clangSema
        clangAnalysis
        clangAST
        clangBasic
        clangEdit
        clangLex
        clangTooling
        LLVMipo
        LLVMScalarOpts
        LLVMInstCombine
        LLVMTransformUtils
        LLVMAnalysis
        LLVMTarget
        LLVMOption
        LLVMMCParser
        LLVMMC
        LLVMObject
        LLVMBitReader
        LLVMCore
        LLVMSupport)
endif(LINK_LLVM_SHARED)

#
# Setup threads library
#
find_package(Threads REQUIRED)

#
# Setup yaml-cpp
#
message(STATUS "Checking for yaml-cpp...")
if(APPLE)
find_package(PkgConfig)
if(PKG_CONFIG_FOUND)
    pkg_check_modules(YAML_CPP yaml-cpp)
    find_path(YAML_CPP_INCLUDE_DIR
            NAMES yaml.h
	    PATHS ${YAML_CPP_INCLUDE_DIR} /usr/local/include/yaml-cpp)
    find_library(YAML_CPP_LIBRARY
            NAMES yaml-cpp
	    PATHS ${YAML_CPP_LIBRARIES} /usr/local/lib)
    set(YAML_CPP_LIBRARY_DIR /usr/local/lib)
endif()
else(APPLE)
    find_package(yaml-cpp REQUIRED)
endif(APPLE)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -std=c++17 -Wno-unused-parameter -Wno-unused-private-field")
# disable the -werreor flag
#add_compile_options(-Werror -Wno-error=format-security)

link_directories(${LLVM_LIBRARY_DIR} ${YAML_CPP_LIBRARY_DIR})

#
# Setup thirdparty sources
#
set(THIRDPARTY_HEADERS_DIR ${PROJECT_SOURCE_DIR}/thirdparty/)

#
# Configure clang-uml executable version
#
file(MAKE_DIRECTORY ${PROJECT_BINARY_DIR}/src/version)
configure_file(src/version.h.in ${PROJECT_BINARY_DIR}/src/version/version.h)

#
# Handle various compiler quirks
#
if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    execute_process(COMMAND gcc --print-file-name=include
                    OUTPUT_STRIP_TRAILING_WHITESPACE
                    OUTPUT_VARIABLE GCC_STDDEF_INCLUDE)
    message(STATUS "FOUND GCC STDDEF INCLUDE ${GCC_STDDEF_INCLUDE}")
    include_directories(${GCC_STDDEF_INCLUDE})
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I${GCC_STDDEF_INCLUDE}")
endif()

message(STATUS "Using CMAKE_CXX_FLAGS: ${CMAKE_CXX_FLAGS}")


#
# Setup include directories
#
include_directories(${LLVM_INCLUDE_DIRS})
include_directories(${CLANG_UML_INSTALL_INCLUDE_DIR})
include_directories(${YAML_CPP_INCLUDE_DIRS})
include_directories(${UML_HEADERS_DIR})
include_directories(${THIRDPARTY_HEADERS_DIR})
include_directories(${PROJECT_SOURCE_DIR}/src/)
include_directories(${PROJECT_BINARY_DIR}/src/version)


#
# Generate source list dynamically
#
file(GLOB_RECURSE SOURCES src/*.cc include/*.h)
set(MAIN_SOURCE_FILE ${CMAKE_CURRENT_SOURCE_DIR}/src/main.cc)
list(REMOVE_ITEM SOURCES ${MAIN_SOURCE_FILE})


#
# Define library target for linking with test cases and output executable
#
add_library(clang-umllib OBJECT ${SOURCES})

#
# Define the target executable clang-uml
#
add_executable(clang-uml ${MAIN_SOURCE_FILE})
target_link_libraries(clang-uml
        ${YAML_CPP_LIBRARIES}
        ${LIBTOOLING_LIBS}
        clang-umllib
        Threads::Threads)

target_compile_features(clang-uml PRIVATE cxx_std_17)

#
# Setup install options
#
include(GNUInstallDirs)

install(TARGETS clang-uml DESTINATION ${CMAKE_INSTALL_BINDIR})
install(FILES LICENSE.md DESTINATION ${CMAKE_INSTALL_DOCDIR})
install(FILES README.md DESTINATION ${CMAKE_INSTALL_DOCDIR})

#
# Enable testing via CTest
#
option(BUILD_TESTS "" ON)
if(BUILD_TESTS)
  enable_testing()
  add_subdirectory(tests)
endif(BUILD_TESTS)

**Comment by XueshiQiao** [comment]
> **use follwing cmake file will fix the above issuse.**
> 
> cmake_minimum_required(VERSION 3.12)
> 
> # Project name
> project(clang-uml)
> 
> # CMake standard defines
> set(CMAKE_EXPORT_COMPILE_COMMANDS ON) set(CMAKE_CXX_STANDARD 17) set(CMAKE_CXX_COMPILER /usr/local/Cellar/llvm/15.0.6/bin/clang++ CACHE FILEPATH "Path to C++ compiler")
> 
> set(CMAKE_VERBOSE_MAKEFILE OFF) set(CMAKE_FIND_DEBUG_MODE OFF) if(APPLE) set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES}) endif(APPLE)
> 
> # clang-uml custom defines
> set(CLANG_UML_INSTALL_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/include) set(CLANG_UML_INSTALL_BIN_DIR ${PROJECT_SOURCE_DIR}/bin) set(UML_HEADERS_DIR ${PROJECT_SOURCE_DIR}/src/uml)
> 
> # CMake build options
> option(LINK_LLVM_SHARED "Should LLVM be linked using shared libraries or statically" ON) #set(LLVM_CONFIG_EXECUTABLE "/usr/local/Cellar/llvm/15.0.6/lib/cmake/llvm" CACHE FILEPATH "Path to custom llvm-config executable") set(LLVM_VERSION CACHE STRING "Path to custom llvm-config executable") set(GIT_VERSION "0.3.0" CACHE STRING "clang-uml version")
> 
> #export CXX=/usr/local/Cellar/llvm/15.0.6/bin/clang++
> 
> # Setup LLVM
> message(STATUS "Checking for LLVM and Clang...") if(LLVM_PREFIX) message(STATUS "Using llvm-config from ${LLVM_CONFIG_PATH}") set(LIBCLANG_LLVM_CONFIG_EXECUTABLE ${LLVM_CONFIG_PATH}) set(LLVM_CONFIG_BINARY ${LLVM_CONFIG_PATH}) endif(LLVM_PREFIX)
> 
> find_package(LLVM ${LLVM_VERSION} CONFIG REQUIRED)
> 
> list(APPEND CMAKE_MODULE_PATH ${LLVM_DIR}) include(AddLLVM)
> 
> message(STATUS "Found LLVM ${LLVM_PACKAGE_VERSION}") message(STATUS "Using LLVMConfig.cmake in: ${LLVM_DIR}") message(STATUS "LLVM library dir: ${LLVM_LIBRARY_DIR}")
> 
> if(LINK_LLVM_SHARED) set(LIBTOOLING_LIBS clang-cpp LLVM) else(LINK_LLVM_SHARED) set(LIBTOOLING_LIBS clangLex clangFrontend clangSerialization clangDriver clangParse clangSema clangAnalysis clangAST clangBasic clangEdit clangLex clangTooling LLVMipo LLVMScalarOpts LLVMInstCombine LLVMTransformUtils LLVMAnalysis LLVMTarget LLVMOption LLVMMCParser LLVMMC LLVMObject LLVMBitReader LLVMCore LLVMSupport) endif(LINK_LLVM_SHARED)
> 
> # Setup threads library
> find_package(Threads REQUIRED)
> 
> # Setup yaml-cpp
> message(STATUS "Checking for yaml-cpp...") if(APPLE) find_package(PkgConfig) if(PKG_CONFIG_FOUND) pkg_check_modules(YAML_CPP yaml-cpp) find_path(YAML_CPP_INCLUDE_DIR NAMES yaml.h PATHS ${YAML_CPP_INCLUDE_DIR} /usr/local/include/yaml-cpp) find_library(YAML_CPP_LIBRARY NAMES yaml-cpp PATHS ${YAML_CPP_LIBRARIES} /usr/local/lib) set(YAML_CPP_LIBRARY_DIR /usr/local/lib) endif() else(APPLE) find_package(yaml-cpp REQUIRED) endif(APPLE)
> 
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -std=c++17 -Wno-unused-parameter -Wno-unused-private-field")
> 
> # disable the -werreor flag
> #add_compile_options(-Werror -Wno-error=format-security)
> 
> link_directories(${LLVM_LIBRARY_DIR} ${YAML_CPP_LIBRARY_DIR})
> 
> # Setup thirdparty sources
> set(THIRDPARTY_HEADERS_DIR ${PROJECT_SOURCE_DIR}/thirdparty/)
> 
> # Configure clang-uml executable version
> file(MAKE_DIRECTORY ${PROJECT_BINARY_DIR}/src/version) configure_file(src/version.h.in ${PROJECT_BINARY_DIR}/src/version/version.h)
> 
> # Handle various compiler quirks
> if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU") execute_process(COMMAND gcc --print-file-name=include OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE GCC_STDDEF_INCLUDE) message(STATUS "FOUND GCC STDDEF INCLUDE ${GCC_STDDEF_INCLUDE}") include_directories(${GCC_STDDEF_INCLUDE}) set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I${GCC_STDDEF_INCLUDE}") endif()
> 
> message(STATUS "Using CMAKE_CXX_FLAGS: ${CMAKE_CXX_FLAGS}")
> 
> # Setup include directories
> include_directories(${LLVM_INCLUDE_DIRS}) include_directories(${CLANG_UML_INSTALL_INCLUDE_DIR}) include_directories(${YAML_CPP_INCLUDE_DIRS}) include_directories(${UML_HEADERS_DIR}) include_directories(${THIRDPARTY_HEADERS_DIR}) include_directories(${PROJECT_SOURCE_DIR}/src/) include_directories(${PROJECT_BINARY_DIR}/src/version)
> 
> # Generate source list dynamically
> file(GLOB_RECURSE SOURCES src/_.cc include/_.h) set(MAIN_SOURCE_FILE ${CMAKE_CURRENT_SOURCE_DIR}/src/main.cc) list(REMOVE_ITEM SOURCES ${MAIN_SOURCE_FILE})
> 
> # Define library target for linking with test cases and output executable
> add_library(clang-umllib OBJECT ${SOURCES})
> 
> # Define the target executable clang-uml
> add_executable(clang-uml ${MAIN_SOURCE_FILE}) target_link_libraries(clang-uml ${YAML_CPP_LIBRARIES} ${LIBTOOLING_LIBS} clang-umllib Threads::Threads)
> 
> target_compile_features(clang-uml PRIVATE cxx_std_17)
> 
> # Setup install options
> include(GNUInstallDirs)
> 
> install(TARGETS clang-uml DESTINATION ${CMAKE_INSTALL_BINDIR}) install(FILES LICENSE.md DESTINATION ${CMAKE_INSTALL_DOCDIR}) install(FILES README.md DESTINATION ${CMAKE_INSTALL_DOCDIR})
> 
> # Enable testing via CTest
> option(BUILD_TESTS "" ON) if(BUILD_TESTS) enable_testing() add_subdirectory(tests) endif(BUILD_TESTS)


It's better use  code block
