### ISSUE TITLE
Several enhancement suggestions 

### ISSUE THREAD

**Issue by bveldhoen** [bkryza/clang-uml#68]
Hi Bartek,

I've been really impressed with this repository, great work! I think this can be really useful and timesaving.

I have used it on an existing codebase, and ran into a few improvements that might make things even better:
* When providing both the -c,--config and the -d,--compile-database options, the value for the latter is ignored, i.e. the value from the config file is always used, and if it's not specified in the config file, the value '.' is used. Perhaps this can be improved by always overriding the compile-database when it is provided on the command line.
* The glob path seems currently to be relative to the current working dir, I would expect it to be relative to the .clang-uml config file (but this may actually be by design).
* I'm currently adding .clang-uml files per project subfolder. All these .clang-uml files are very similar, in that they try to achieve a class diagram for all classes in the namespace corresponding to that subfolder, with the context limited to all classes within. This is somewhat tedious, as it requires repeating the names of the classes, etc. Would it be an option to add a possibiity to generate diagrams per subfolder, with the option to specify more general options (such as limit the context to classes found within that subfolder, or generate a class diagram per class with context set to that class and limited to that namespace). I haven't figured out yet what the other options need to be, but I can probably elaborate at a later stage.

Thanks,
Kind regards,

Bram Veldhoen

**Comment by bkryza** [comment]
@bveldhoen Thanks for the comments!

The first 2 bullets are most probably bugs, I've created separate issues for them.

As to the last one, yes currently the usability of the configuration has a lot of room for improvement. However please note that most of the options are `inheritable` from the root of the config file to the diagrams - the list of options that should be inheritable is [here](https://github.com/bkryza/clang-uml/blob/master/src/config/config.h#L126-L148).

Also it's possible to have one `.clang-uml` at the top and include into it separate YAML files for each diagram, for instance consider the `clang-uml`'s [.clang-uml](https://github.com/bkryza/clang-uml/blob/master/.clang-uml) file...

**Comment by bramv72** [comment]
@bkryza I've tested the fix for --compile-database, and it works. Thanks for fixing, and so quickly!

I ran into another small issue: some generated plantuml iles contain full paths, i.e.:
`C_0001116672667747658761 -> C_0001116672667747658761 : for_each((lambda at /home/bramv/src/projects/xxx.cpp:1227:14) &&)
`
This might be specific for lambdas, not sure?

**Comment by bveldhoen** [comment]
@bkryza I've tested the fix for --compile-database, and it works. Thanks for fixing, and so quickly!

I ran into another small issue: some generated plantuml iles contain full paths, i.e.:
C_0001116672667747658761 -> C_0001116672667747658761 : for_each((lambda at /home/bramv/src/projects/xxx.cpp:1227:14) &&) 
This might be specific for lambdas, not sure?

**Comment by bkryza** [comment]
@bveldhoen Thanks again for these suggestions. The first 2 are now fixed in the master, I'll consider the third one in the future - closing this issue for now...
