### ISSUE TITLE
Add support for C++20 concepts

### ISSUE THREAD

**Issue by bkryza** [bkryza/clang-uml#96]
Since Clang/LLVM provides API for traversing C++20 concepts:

```cpp
bool TraverseTypeConstraint(const TypeConstraint *C);
bool TraverseConceptRequirement(concepts::Requirement *R);
bool TraverseConceptTypeRequirement(concepts::TypeRequirement *R);
bool TraverseConceptExprRequirement(concepts::ExprRequirement *R);
bool TraverseConceptNestedRequirement(concepts::NestedRequirement *R);
```

it should be fairly straightforward to add concepts to the UML diagrams generated by `clang-uml`.

The question is how to best render concepts in UML, one option would be to render special class templates with stereotype `<<concept>>` and whose body contains all the required expressions, e.g.:

```plantuml
@startuml
class "Serializable<T>" as C_0
class C_0 <<concept>> {
(std::ostream& ostr, T x)
----
* {x.serialize()} noexcept;
* ostr << x;
}

class "Protocol<Serializable Msg...>" as C_1

class C_1 {
- m_messageSet : std::tuple<Msg...>
}

C_1 ..> C_0 
@enduml
```

**Comment by SreenathUS** [comment]
Where I can find the usage instructions for windows? 
I have installed the windows clang-uml exe but do not see neither any clang-uml app nore the cmd tool available.

**Comment by bkryza** [comment]
There are no specific instructions for Windows yet.

P.S. Please create issues on GitHub so that they remain for reference for
other users..

Regards,
Bartek Kryza
